# CloudSnap KCC Demo - Namespace Configuration
# This file configures the Kubernetes namespace with Config Connector context

apiVersion: v1
kind: Namespace
metadata:
  name: cloudsnap
  annotations:
    # Default project for all KCC resources in this namespace
    cnrm.cloud.google.com/project-id: "${PROJECT_ID}"
  labels:
    app: cloudsnap
    managed-by: kcc
---
# ConfigConnectorContext configures how Config Connector operates in this namespace
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: cloudsnap
spec:
  # Use the project-level Google Service Account
  googleServiceAccount: "kcc-controller@${PROJECT_ID}.iam.gserviceaccount.com"