# CloudSnap KCC Demo - Service Accounts
# IAM service accounts for different components

# Service account for upload operations (frontend/API)
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cloudsnap-uploader
  namespace: cloudsnap
  annotations:
    cnrm.cloud.google.com/state-into-spec: absent
  labels:
    app: cloudsnap
    component: iam
    role: uploader
spec:
  displayName: "CloudSnap Uploader Service Account"
  description: "Service account for handling file uploads and signed URL generation"
---
# Service account for the media processor
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cloudsnap-processor
  namespace: cloudsnap
  annotations:
    cnrm.cloud.google.com/state-into-spec: absent
  labels:
    app: cloudsnap
    component: iam
    role: processor
spec:
  displayName: "CloudSnap Processor Service Account"
  description: "Service account for media processing jobs"
---
# Service account for the API service
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cloudsnap-api
  namespace: cloudsnap
  annotations:
    cnrm.cloud.google.com/state-into-spec: absent
  labels:
    app: cloudsnap
    component: iam
    role: api
spec:
  displayName: "CloudSnap API Service Account"
  description: "Service account for the REST API service"